### ISSUE TITLE
Getting error when building vignette

### ISSUE THREAD

**Issue by seandavi** [waldronlab/enrichOmics#4]
```
   --- re-building ‘enrichOmics.Rmd’ using rmarkdown
   Quitting from lines 678-680 (enrichOmics.Rmd)
   Error: processing vignette 'enrichOmics.Rmd' failed with diagnostics:
   Error loading pathway data. Please retry the operation at a later time.
   --- failed re-building ‘enrichOmics.Rmd’

   SUMMARY: processing the following file failed:
     ‘enrichOmics.Rmd’

   Error: Vignette re-building failed.
   Execution halted
```

**Comment by seandavi** [comment]
cc: @lwaldron @LiNk-NY

**Comment by seandavi** [comment]
Looks like this has to do with the web service being down at the moment (https://graphiteweb.bio.unipd.it/). You can reproduce the error by:
h = graphite:::loadPathways("hsa", "kegg")

Note that the result is cached, so this problem only arises on a clean system.

**Comment by lgeistlinger** [comment]
Thanks @seandavi. 
Going to give the `graphite` maintainer a ping.
If the problem persist over the course of this week, we can replace line 678:
```
hsa.grn <- compileGRN(org="hsa", db="kegg")
```
by
```
hsa.grn <- compileGRN(org="hsa", db="kegg", kegg.native=TRUE)
```
to directly compile from KEGG.

**Comment by lwaldron** [comment]
I don't think we can wait the week; the AMI will be frozen as soon as we can get this and other final issues resolved. Would you go ahead and do the line 678 replacement for a quick fix @lgeistlinger?

**Comment by lgeistlinger** [comment]
Sure

**Comment by lgeistlinger** [comment]
Done: 2f3fb816a746a67ca8e897280025f7057f0ab524
