### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/enrichOmics#8]
Vignette did not build successfully due to timeout last time, probably network issues. Monitor https://github.com/waldronlab/enrichOmics/runs/914323890?check_suite_focus=true

**Comment by lwaldron** [comment]
Note this is still a blocker as the Docker image hasn't been updated. @lgeistlinger @LiNk-NY if my latest attempt doesn't work, can you keep trying if I am too busy with conference today?

**Comment by lwaldron** [comment]
@lgeistlinger can you implement a workaround for an apparent problem with rest.kegg.jp?
```
Quitting from lines 575-577 (Geistlinger_enrichOmics.Rmd) 
  Error: processing vignette 'Geistlinger_enrichOmics.Rmd' failed with diagnostics:
  Timeout was reached: [rest.kegg.jp] Connection timed out after 10000 milliseconds
  --- failed re-building ‘Geistlinger_enrichOmics.Rmd’
```

**Comment by lgeistlinger** [comment]
I'll be looking into that and see what I can reproduce locally.

**Comment by lwaldron** [comment]
If you have to, you could build the Docker image locally and push to Dockerhub, just so we get an image that has the Suggests packages used in the vignette installed...

**Comment by lgeistlinger** [comment]
no such problems when downloading from KEGG locally. Either a docker issue or just a hickup / network problem on the server. I'll give it another try (re-run), otherwise I'll switch to a set of pre-downloaded gene sets.

**Comment by lwaldron** [comment]
Maybe KEGG blocked some Google Cloud IP ranges... you could even just set `--no-build-vignettes` for now to get it a built image.

**Comment by lgeistlinger** [comment]
I didn't do much of a change except replacing the docker tag, but now it seems to build. At least it passed the check step where it failed before.

**Comment by lgeistlinger** [comment]
built clean.
